package main

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Gong-Yang/g-micor/pgsql"
	"github.com/Gong-Yang/g-micor/util/random"
)

var UserStore = pgsql.GetTable[User]("users")

func main() {
	err := pgsql.Init("postgres://postgres:123456@localhost:5432/postgres")
	if err != nil {
		panic(err)
	}
	//user := &User{Name: "John Doe", Email: "john.doe@example.com", Age: 30}
	Many()
}
func Many() {
	arr, err := UserStore.Find(context.Background(),
		pgsql.Where("name = $1", "John8").
			And("age > $1", 25))
	if err != nil {
		panic(err)
	}
	marshal, err := json.Marshal(arr)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(marshal))

	u1 := GenUser()
	u2 := GenUser()
	UserStore.InsertMany(context.Background(), []*User{u1, u2})
	println(u1.ID, *u1.Name)
	println(u2.ID, *u2.Name)
}
func OneExample() {
	user := GenUser()
	err := UserStore.InsertOne(context.Background(), user)
	if err != nil {
		panic(err)
	}
	println(user.ID)
	res, err := UserStore.FindByID(context.Background(), user.ID)
	if err != nil {
		panic(err)
	}
	marshal, _ := json.Marshal(res)
	fmt.Println(string(marshal))
}

//CREATE TABLE users (
//id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//name VARCHAR(100) NOT NULL,
//email VARCHAR(100) NOT NULL,
//age INT,
//created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
//address JSONB,
//addrs JSONB,
//embedding BYTEA
//);

type User struct {
	ID        int64      `db:"id" json:"id,omitempty"`
	Name      *string    `db:"name" json:"name,omitempty"`
	Email     string     `db:"email" json:"email,omitempty"`
	Age       int32      `db:"age" json:"age,omitempty"`
	CreatedAt time.Time  `db:"created_at" json:"createdAt"`
	Address   *Address   `db:"address" json:"address"`
	Addrs     []*Address `db:"addrs" json:"addrs,omitempty"`
	Embedding []byte     `db:"embedding" json:"embedding,omitempty"`
}
type Address struct {
	Street string `db:"street" json:"street,omitempty"`
	Number int    `db:"number" json:"number,omitempty"`
}

func (u User) TableName() string {
	return "users"
}

func GenUser() *User {
	name := random.ShortUUID()
	now := time.Now()
	return &User{
		Name:  &name,
		Email: "john5@example.com",
		Age:   31,
		Address: &Address{
			Street: "gg",
			Number: 6,
		},
		CreatedAt: now,
		Addrs: []*Address{
			{
				Street: "gg1",
				Number: 1,
			},
			{
				Street: "gg2",
				Number: 2,
			},
		},
		Embedding: []byte{1, 2, 3, 255},
	}
}
