// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.3
// source: contract/order/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       int32                  `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_contract_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_contract_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_contract_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReq) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type CreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRes) Reset() {
	*x = CreateRes{}
	mi := &file_contract_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRes) ProtoMessage() {}

func (x *CreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_contract_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRes.ProtoReflect.Descriptor instead.
func (*CreateRes) Descriptor() ([]byte, []int) {
	return file_contract_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRes) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

var File_contract_order_order_proto protoreflect.FileDescriptor

const file_contract_order_order_proto_rawDesc = "" +
	"\n" +
	"\x1acontract/order/order.proto\x12\x05order\"=\n" +
	"\tCreateReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\agoodsId\x18\x02 \x01(\x05R\agoodsId\"%\n" +
	"\tCreateRes\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId27\n" +
	"\x05Order\x12.\n" +
	"\x06Create\x12\x10.order.CreateReq\x1a\x10.order.CreateRes\"\x00B-Z+github.com/Gong-Yang/g-micor/contract/orderb\x06proto3"

var (
	file_contract_order_order_proto_rawDescOnce sync.Once
	file_contract_order_order_proto_rawDescData []byte
)

func file_contract_order_order_proto_rawDescGZIP() []byte {
	file_contract_order_order_proto_rawDescOnce.Do(func() {
		file_contract_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_order_order_proto_rawDesc), len(file_contract_order_order_proto_rawDesc)))
	})
	return file_contract_order_order_proto_rawDescData
}

var file_contract_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_order_order_proto_goTypes = []any{
	(*CreateReq)(nil), // 0: order.CreateReq
	(*CreateRes)(nil), // 1: order.CreateRes
}
var file_contract_order_order_proto_depIdxs = []int32{
	0, // 0: order.Order.Create:input_type -> order.CreateReq
	1, // 1: order.Order.Create:output_type -> order.CreateRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_order_order_proto_init() }
func file_contract_order_order_proto_init() {
	if File_contract_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_order_order_proto_rawDesc), len(file_contract_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_order_order_proto_goTypes,
		DependencyIndexes: file_contract_order_order_proto_depIdxs,
		MessageInfos:      file_contract_order_order_proto_msgTypes,
	}.Build()
	File_contract_order_order_proto = out.File
	file_contract_order_order_proto_goTypes = nil
	file_contract_order_order_proto_depIdxs = nil
}
