// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.3
// source: contract/notify/notify.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_contract_notify_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_notify_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_contract_notify_notify_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_contract_notify_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_notify_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_contract_notify_notify_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendEmailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_contract_notify_notify_proto protoreflect.FileDescriptor

const file_contract_notify_notify_proto_rawDesc = "" +
	"\n" +
	"\x1ccontract/notify/notify.proto\x12\x06notify\"<\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"A\n" +
	"\x11SendEmailResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2L\n" +
	"\x06Notify\x12B\n" +
	"\tSendEmail\x12\x18.notify.SendEmailRequest\x1a\x19.notify.SendEmailResponse\"\x00B.Z,github.com/Gong-Yang/g-micor/contract/notifyb\x06proto3"

var (
	file_contract_notify_notify_proto_rawDescOnce sync.Once
	file_contract_notify_notify_proto_rawDescData []byte
)

func file_contract_notify_notify_proto_rawDescGZIP() []byte {
	file_contract_notify_notify_proto_rawDescOnce.Do(func() {
		file_contract_notify_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_notify_notify_proto_rawDesc), len(file_contract_notify_notify_proto_rawDesc)))
	})
	return file_contract_notify_notify_proto_rawDescData
}

var file_contract_notify_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_notify_notify_proto_goTypes = []any{
	(*SendEmailRequest)(nil),  // 0: notify.SendEmailRequest
	(*SendEmailResponse)(nil), // 1: notify.SendEmailResponse
}
var file_contract_notify_notify_proto_depIdxs = []int32{
	0, // 0: notify.Notify.SendEmail:input_type -> notify.SendEmailRequest
	1, // 1: notify.Notify.SendEmail:output_type -> notify.SendEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_notify_notify_proto_init() }
func file_contract_notify_notify_proto_init() {
	if File_contract_notify_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_notify_notify_proto_rawDesc), len(file_contract_notify_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_notify_notify_proto_goTypes,
		DependencyIndexes: file_contract_notify_notify_proto_depIdxs,
		MessageInfos:      file_contract_notify_notify_proto_msgTypes,
	}.Build()
	File_contract_notify_notify_proto = out.File
	file_contract_notify_notify_proto_goTypes = nil
	file_contract_notify_notify_proto_depIdxs = nil
}
