// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.3
// source: g-micor/discover/discover.proto

package discover

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务发现请求
type Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          string                 `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`     // 请求者的地址
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"` // 请求者需要发现的服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Req) Reset() {
	*x = Req{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Req) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

// 服务发现响应
type Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"` // 服务名称
	Addr          []string               `protobuf:"bytes,2,rep,name=addr,proto3" json:"addr,omitempty"`     // 服务地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resp) Reset() {
	*x = Resp{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{1}
}

func (x *Resp) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Resp) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

// 服务注册请求
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          string                 `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Servers       []string               `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"` // 服务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RegisterReq) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

// 服务注册响应
type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{3}
}

// ping 请求
type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{4}
}

// ping 响应
type PingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{5}
}

// 服务新增通知请求
type NotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`     // 通知类型 1. register 服务上线 2. del 服务下线
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"` // 服务名
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`     // 服务地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotifyReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *NotifyReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// 服务新增通知响应
type NotifyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRes) Reset() {
	*x = NotifyRes{}
	mi := &file_g_micor_discover_discover_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRes) ProtoMessage() {}

func (x *NotifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_g_micor_discover_discover_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRes.ProtoReflect.Descriptor instead.
func (*NotifyRes) Descriptor() ([]byte, []int) {
	return file_g_micor_discover_discover_proto_rawDescGZIP(), []int{7}
}

var File_g_micor_discover_discover_proto protoreflect.FileDescriptor

const file_g_micor_discover_discover_proto_rawDesc = "" +
	"\n" +
	"\x1fg-micor/discover/discover.proto\x12\bdiscover\"1\n" +
	"\x03Req\x12\x12\n" +
	"\x04port\x18\x01 \x01(\tR\x04port\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\"2\n" +
	"\x04Resp\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x12\n" +
	"\x04addr\x18\x02 \x03(\tR\x04addr\";\n" +
	"\vRegisterReq\x12\x12\n" +
	"\x04port\x18\x01 \x01(\tR\x04port\x12\x18\n" +
	"\aservers\x18\x03 \x03(\tR\aservers\"\r\n" +
	"\vRegisterRes\"\t\n" +
	"\aPingReq\"\t\n" +
	"\aPingRes\"K\n" +
	"\tNotifyReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\"\v\n" +
	"\tNotifyRes2s\n" +
	"\bRegister\x12:\n" +
	"\bRegister\x12\x15.discover.RegisterReq\x1a\x15.discover.RegisterRes\"\x00\x12+\n" +
	"\bDiscover\x12\r.discover.Req\x1a\x0e.discover.Resp\"\x002\x7f\n" +
	"\x06Client\x12.\n" +
	"\x04Ping\x12\x11.discover.PingReq\x1a\x11.discover.PingRes\"\x00\x12E\n" +
	"\x17SubscribeServerRegister\x12\x13.discover.NotifyReq\x1a\x13.discover.NotifyRes\"\x00B'Z%github.com/Gong-Yang/g-micor/discoverb\x06proto3"

var (
	file_g_micor_discover_discover_proto_rawDescOnce sync.Once
	file_g_micor_discover_discover_proto_rawDescData []byte
)

func file_g_micor_discover_discover_proto_rawDescGZIP() []byte {
	file_g_micor_discover_discover_proto_rawDescOnce.Do(func() {
		file_g_micor_discover_discover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_g_micor_discover_discover_proto_rawDesc), len(file_g_micor_discover_discover_proto_rawDesc)))
	})
	return file_g_micor_discover_discover_proto_rawDescData
}

var file_g_micor_discover_discover_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_g_micor_discover_discover_proto_goTypes = []any{
	(*Req)(nil),         // 0: discover.Req
	(*Resp)(nil),        // 1: discover.Resp
	(*RegisterReq)(nil), // 2: discover.RegisterReq
	(*RegisterRes)(nil), // 3: discover.RegisterRes
	(*PingReq)(nil),     // 4: discover.PingReq
	(*PingRes)(nil),     // 5: discover.PingRes
	(*NotifyReq)(nil),   // 6: discover.NotifyReq
	(*NotifyRes)(nil),   // 7: discover.NotifyRes
}
var file_g_micor_discover_discover_proto_depIdxs = []int32{
	2, // 0: discover.Register.Register:input_type -> discover.RegisterReq
	0, // 1: discover.Register.Discover:input_type -> discover.Req
	4, // 2: discover.Client.Ping:input_type -> discover.PingReq
	6, // 3: discover.Client.SubscribeServerRegister:input_type -> discover.NotifyReq
	3, // 4: discover.Register.Register:output_type -> discover.RegisterRes
	1, // 5: discover.Register.Discover:output_type -> discover.Resp
	5, // 6: discover.Client.Ping:output_type -> discover.PingRes
	7, // 7: discover.Client.SubscribeServerRegister:output_type -> discover.NotifyRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_g_micor_discover_discover_proto_init() }
func file_g_micor_discover_discover_proto_init() {
	if File_g_micor_discover_discover_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_g_micor_discover_discover_proto_rawDesc), len(file_g_micor_discover_discover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_g_micor_discover_discover_proto_goTypes,
		DependencyIndexes: file_g_micor_discover_discover_proto_depIdxs,
		MessageInfos:      file_g_micor_discover_discover_proto_msgTypes,
	}.Build()
	File_g_micor_discover_discover_proto = out.File
	file_g_micor_discover_discover_proto_goTypes = nil
	file_g_micor_discover_discover_proto_depIdxs = nil
}
