package main

import (
	"context"
	"encoding/json"
	"fmt"
	"time"
)

var UserStore = GetTable[User]()

func main() {
	err := Init("postgres://gg:123456@localhost:5432/ggyynet")
	if err != nil {
		panic(err)
	}
	//user := &User{Name: "John Doe", Email: "john.doe@example.com", Age: 30}
	user := &User{Name: "John3", Email: "john5@example.com", Age: 31, CreatedAt: time.Now(),
		Address: &Address{
			Street: "gg",
			Number: 6,
		}}
	err = UserStore.InsertOne(context.Background(), user)
	if err != nil {
		panic(err)
	}
	println(user.ID)
	res, err := UserStore.FindById(context.Background(), user.ID)
	if err != nil {
		panic(err)
	}
	marshal, _ := json.Marshal(res)
	fmt.Println(string(marshal))
}

//CREATE TABLE users (
//id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//name VARCHAR(100) NOT NULL,
//email VARCHAR(100) UNIQUE NOT NULL,
//age INT,
//created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
//);

type User struct {
	ID        int64     `db:"id" json:"id,omitempty"`
	Name      string    `db:"name" json:"name,omitempty"`
	Email     string    `db:"email" json:"email,omitempty"`
	Age       int32     `db:"age" json:"age,omitempty"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	Address   *Address  `db:"address" json:"address"`
}
type Address struct {
	Street string `db:"street" json:"street,omitempty"`
	Number int    `db:"number" json:"number,omitempty"`
}

func (u User) TableName() string {
	return "users"
}
